### ISSUE TITLE
The example in the README does not match with the current master code

### ISSUE THREAD

**Issue by Dima-369** [GoNZooo/odin-cli#7]
`parse_arguments_as_type` was changed to return 3 values, but the README uses it, so that it only has 2.

**Comment by GoNZooo** [comment]
Should be fixed in f9ece6a3739944357ee27dbcfaf559fe0c378892

**Comment by Dima-369** [comment]
Thanks, works!

It might be really great if the usage example in the README includes a full standalone file with `package main` and the `run_analyze_lock_file()`, so one can try out this library quickly.

**Comment by GoNZooo** [comment]
I think people can figure it out. I also don't want to perpetuate the myth that your package should be called `main` so I wouldn't make that example. I think the existence of a `main` function in the example is enough to indicate that this is indeed a file that you can use to produce a binary and your logic ought to go in that main function.
